name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Archive Build Folder
        run: tar -czvf join.tar.gz .

      - name: Copy Files to Remote Server
        env:
          TARGET_HOST: ${{ secrets.TARGET_HOST }}
          TARGET_DIRECTORY: ${{ secrets.TARGET_DIRECTORY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          scp -o StrictHostKeyChecking=no join.tar.gz $REMOTE_USER@$TARGET_HOST:$TARGET_DIRECTORY

      - name: Deploy on Remote Server
        env:
          TARGET_HOST: ${{ secrets.TARGET_HOST }}
          TARGET_DIRECTORY: ${{ secrets.TARGET_DIRECTORY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$TARGET_HOST "
            tar -xzvf $TARGET_DIRECTORY/join.tar.gz -C $TARGET_DIRECTORY
          "
